-- MySQL Script generated by MySQL Workbench
-- Tue Jun 23 18:03:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catalogo-filme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema catalogo-filme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catalogo-filme` DEFAULT CHARACTER SET utf8 ;
USE `catalogo-filme` ;

-- -----------------------------------------------------
-- Table `catalogo-filme`.`usuarios`
-- status: enum salvo como Integer para delecao logica (1 = ATIVO, 2 = INATIVO)
-- roles/autorizacao: relacao ManyToMany via tabelas `cargos` e `usuario_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo-filme`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `url_image` VARCHAR(255) NULL,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_usuarios_email` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo-filme`.`plataformas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo-filme`.`plataformas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `url_image` VARCHAR(255) NULL,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo-filme`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo-filme`.`generos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo-filme`.`filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo-filme`.`filmes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `diretor` VARCHAR(45) NOT NULL,
  `data_lancamento` DATE NOT NULL,
  `genero_id` INT NOT NULL,
  `plataforma_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_plataforma_filme_idx` (`plataforma_id` ASC),
  INDEX `fk_generos_filme_idx` (`genero_id` ASC),
  CONSTRAINT `fk_plataforma_filme`
    FOREIGN KEY (`plataforma_id`)
    REFERENCES `catalogo-filme`.`plataformas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_generos_filme`
    FOREIGN KEY (`genero_id`)
    REFERENCES `catalogo-filme`.`generos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo-filme`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo-filme`.`avaliacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(255) NOT NULL,
  `url_image` VARCHAR(255) NULL,
  `nota` DOUBLE NOT NULL,
  `usuario_id` INT NOT NULL,
  `filme_id` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_filme_avaliacao_idx` (`filme_id` ASC),
  INDEX `fk_usuario_avaliacao_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_avaliacao`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `catalogo-filme`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_avaliacao`
    FOREIGN KEY (`filme_id`)
    REFERENCES `catalogo-filme`.`filmes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo-filme`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo-filme`.`cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo-filme`.`usuario_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo-filme`.`usuario_cargo` (
  `usuario_id` INT NOT NULL,
  `cargo_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `cargo_id`),
  INDEX `fk_cargo_id_idx` (`cargo_id` ASC),
  CONSTRAINT `fk_cargo_id`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `catalogo-filme`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `catalogo-filme`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Dados iniciais: cargos padrao
-- -----------------------------------------------------
INSERT INTO `catalogo-filme`.`cargos` (`nome`) VALUES ('ROLE_ADMIN');
INSERT INTO `catalogo-filme`.`cargos` (`nome`) VALUES ('ROLE_USER');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
